[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gct"
version = "0.1.0"
description = "A cli tool for ShieldAI"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
authors = [
    {name = "Garrett Shoemaker", email = "garrett.shoemaker3@gmail.com"}
    ]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "black",
    "bandit",
    "safety"
]
[project.scripts]
tool = "cli_tool.main:main"

[dependency-groups]
dev = [
    "bandit>=1.7.10",
    "black>=24.8.0",
    "pre-commit>=3.5.0",
    "pyinstaller>=6.19.0",
    "pytest>=8.3.5",
    "safety>=3.6.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-ra -q"

[tool.bandit]
targets = ["src"]
exclude_dirs = ["tests"]
