name: Build Executables

on:
  push:
  workflow_call:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --name tool-${{ matrix.os }} src/cli_tool/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gct-${{ matrix.os }}
          path: dist/
